# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20151222_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='contry',
            new_name='country',
        ),
    ]
